core/urls.py
from django.conf.urls import url

from . import views
import account

urlpatterns = [
    url(r'^activity/$', views.activity, name='activity'),
    url(r'^ranking/$', views.question_ranking, name='ranking'),
    url(r'^question/$', views.question, name='question'),
    url(r'^question/(?P<id>\d+)/$', views.question_detail, name='question_detail'),
    url(r'^topic/$', views.topic, name='topic'),
    url(r'^people/edit/$', account.views.profile_edit, name='profile_edit'),
    url(r'^people/follow/$', views.user_follow, name='user_follow'),
    url(r'^people/(?P<username>[-\w]+)/$', views.people, name='people'),
    url(r'^question/ask/$', views.create_question, name='ask'),
]

fakezhihu/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from core.views import index, search
urlpatterns = [
    # Examples:
    # url(r'^$', index, name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls',
                              namespace='account')),

    url(r'^', include('core.urls')),
    # 主页
    url(r'^$', index, name='index'),
    url(r'^q/$', search, name='search'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.core.files import File

auth_user = User

class Profile(models.Model):
    SEX_CHOICES = (
        ('m', '男'),
        ('f', '女')
    )
    user = models.OneToOneField(auth_user)
    photo = models.ImageField(upload_to='users', blank=True)
    sex = models.CharField(max_length=10, choices=SEX_CHOICES, default='m')
    introduction = models.CharField(max_length=20, blank=True)
    address = models.CharField(max_length=20, blank=True)
    industry = models.CharField(max_length=20, blank=True)
    education = models.CharField(max_length=20, blank=True)
    website = models.URLField(blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)

    @property
    def photo_url(self):
        if self.photo and hasattr(self.photo, 'url'):
            return self.photo.url
        return '%s%s' % (settings.MEDIA_URL, 'users/default.png')

    def save(self, *args, **kwargs):
        if not self.photo:
            with open(settings.MEDIA_ROOT + 'users/default.png', 'rb') as f:
                self.photo.save('default.png', File(f), save=False)

        super(Profile, self).save(*args, **kwargs)



class Contact(models.Model):
    user_from = models.ForeignKey(auth_user,
                                  related_name='rel_from_set')
    user_to = models.ForeignKey(settings.AUTH_USER_MODEL,
                                related_name='rel_to_set')
    created = models.DateTimeField(auto_now_add=True,
                                   db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{} follows {}'.format(self.user_from, self.user_to)

auth_user.add_to_class('following',
                       models.ManyToManyField('self',
                                              through=Contact,
                                              related_name='followers',
                                              symmetrical=False))

core/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

from taggit.managers import TaggableManager

class Question(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, related_name='questions')
    body = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    topics = TaggableManager()

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('question_detail',
                       args=[self.id])

    def answers_count(self):
        return self.answers.count()


class Answer(models.Model):
    question = models.ForeignKey(Question, related_name='answers')
    author = models.ForeignKey(User, related_name='answers')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    body = models.TextField()

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.body


class Action(models.Model):
    user = models.ForeignKey(User,
                             related_name='actions',
                             db_index=True)
    verb = models.CharField(max_length=255)
    target_ct = models.ForeignKey(ContentType,
                                  blank=True,
                                  null=True,
                                  related_name='target_obj')
    target_id = models.PositiveIntegerField(null=True,
                                            blank=True,
                                            db_index=True)
    target = GenericForeignKey('target_ct', 'target_id')
    created = models.DateTimeField(auto_now_add=True,
                                   db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{self.user} {self.verb} {self.target} at {self.created}'.format(self=self)

    def get_target_model_name(self):
        return self.target_ct.model_class().__name__

core/forms.py
from django import forms

from .models import Answer, Question

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('body',)
        labels = {
            'body': '撰写答案',
        }


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('title', 'body')
        labels = {
            'body': '问题描述(可选)',
        }

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.models import User
from django.db.models import Count
from django.views.decorators.http import require_POST
from django.contrib import messages

from taggit.models import Tag

from redis import StrictRedis, ConnectionPool

from account.models import Contact
from .models import Question, Action
from .forms import AnswerForm, QuestionForm
from .utils import create_action
from .decorators import ajax_required

pool = ConnectionPool(host=settings.REDIS_HOST,
                      port=settings.REDIS_PORT,
                      db=settings.REDIS_DB)
r = StrictRedis(connection_pool=pool)


@login_required
def activity(request):
    actions = Action.objects.exclude(user=request.user)
    following_ids = request.user.following.values_list('id', flat=True)
    if following_ids:
        actions = actions.filter(user_id__in=following_ids) \
            .select_related('user', 'user__profile') \
            .prefetch_related('target')

    return render(request,
                  'core/activity.html',
                  {'actions': actions})


@login_required
def question(request):
    questions = Question.objects.all()

    return render(request,
                  'core/question.html',
                  {'questions': questions})


@login_required
def question_ranking(request):
    question_ranking = r.zrange('question_ranking', 0, -1,
                                desc=True)[:10]
    question_ranking_ids = [int(id) for id in question_ranking]
    most_viewd = list(Question.objects.filter(id__in=question_ranking_ids))
    most_viewd.sort(key=lambda x: question_ranking_ids.index(x.id))

    return render(request,
                  'core/question_rank.html',
                  {'most_viewd': most_viewd})


# 首页视图转到这里
index = question


def question_detail(request, id):
    question = get_object_or_404(Question, pk=id)
    answers = question.answers.all()
    # total_views = r.incr('question:{}:views'.format(question.id))
    # r.zincrby('question_ranking', question.id, 1)

    if request.method == 'POST':
        answer_form = AnswerForm(request.POST)
        '''
        if question.answers.filter(author=request.user).exists():
            messages.error(request, '你已回答过此问题了！')
            return redirect(question)
        '''
        if answer_form.is_valid():
            new_answer = answer_form.save(commit=False)
            new_answer.question = question
            new_answer.author = request.user
            new_answer.save()
            create_action(request.user, '回答了问题', question)
            return redirect(question)
    else:
        answer_form = AnswerForm()
    return render(request,
                  'core/question_detail.html',
                  {'question': question,
                   'answers': answers,
                   'answer_form': answer_form})


@login_required
def topic(request):
    topics = Tag.objects.all()
    return render(request,
                  'core/topics.html',
                  {'topics': topics})


def people(request, username):
    user = get_object_or_404(User, username=username)
    actions = Action.objects.filter(user=user)
    return render(request,
                  'core/people.html',
                  {'user': user, 'actions': actions})


@login_required
def create_question(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            new_question = form.save(commit=False)
            new_question.author = request.user
            new_question.save()
            messages.success(request, '你问了一个问题')
            return redirect(reverse('question'))
    else:
        form = QuestionForm()

    return render(request, 'core/ask.html',
                  {
                      'form': form
                  })


@require_POST
@ajax_required
@login_required
def user_follow(request):
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    if user_id and action:
        try:
            user = User.objects.get(pk=user_id)
            if action == 'follow':
                Contact.objects.get_or_create(user_from=request.user,
                                              user_to=user)
                create_action(request.user, '关注了用户', user)
            else:
                Contact.objects.filter(user_from=request.user,
                                       user_to=user).delete()
            return JsonResponse({'status': 'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status': 'ko'})
    return JsonResponse({'status': 'ko'})


def search(request):
    word = request.GET.get('word')
    if not word:
        return JsonResponse({'error': 'You got nothing'})
    return JsonResponse({'success': 'Will be complete soon!'})

core/templates/core/activity.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}

    {% for action in actions %}
        <div class="ui text container">
            <div class="ui feed">
                {% with user=action.user profile=action.user.profile %}
                    <div class="event">
                        <div class="label">
                            {% if profile.photo %}
                                {% thumbnail profile.photo "40x40" crop="100%" as im %}
                                    <a href="{{ user.get_absolute_url }}">
                                        <img src="{{ im.url }}" alt="{{ user.get_full_name }}">
                                    </a>
                                {% endthumbnail %}
                            {% endif %}
                        </div>
                        <div class="content">
                            <div class="summary">
                                <a href="{{ user.get_absolute_url }}">{{ user.username }}</a>
                                {{ action.verb }}
                                {% if action.target %}
                                    {% with target=action.target %}
                                        <a href="{{ target.get_absolute_url }}">{{ target }}</a>
                                    {% endwith %}
                                {% endif %}
                                <span class="date">{{ action.created|timesince }} ago</span>
                            </div>

                        </div>
                    </div>
                    </div>
                    </div>
                {% endwith %}
    {% empty %}
        <p>你还没有关注任何人哦!</p>
    {% endfor %}
{% endblock %}

core/templates/core/ask.html
{% extends 'base.html' %}

{% load awesome_tags %}
{% load widget_tweaks %}
{% block title %}Ask{% endblock %}
{% block content %}
    <div class="ui container grid" style="padding-top: 5rem">

            <div class="eleven wide column">
                <form class="ui form" action="." method="post">

                    <input type="hidden">{% csrf_token %}</input>
                    <div class="field">
                        <label>标题</label>
                        <input name="title" placeholder="明确的问题" type="text">
                    </div>
                    <div class="field">
                        <label>问题描述</label>
                        <textarea name="body" placeholder="问题背景、详细信息(可选)"></textarea>
                    </div>
                    <div class="field">
                        <label for="">话题</label>
                        <input name="topics" placeholder="添加所属话题，最多5个，用空格分开" type="text">
                    </div>
                    <div class="field">
                        <div class="ui checkbox">
                            <input tabindex="0" name="notify" type="checkbox">
                            <label>有新的回复时通知我?</label>
                        </div>
                    </div>
                    <button class="ui button primary" type="submit">提交你的问题</button>


                </form>
                {% form_errors form %}
            </div>

    </div>
{% endblock %}

core/templates/core/form_errors.html
{% if errors %}
    <div class="ui error message">
        <ul class="list">
            {% for error in errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

core/templates/core/people.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
{{ user.username }}
{% endblock %}
{% block content %}
 <h1>个人主页</h1>
<div id="people_info">
{% with profile=user.profile %}
{% thumbnail profile.photo '100x100' crop='100%' as im %}
    <a href="{{ profile.photo.url }}">
    <img src="{{ im.url }}" alt="用户图像">
    </a>
    {% endthumbnail %}
    <p>{{ user.username }}</p>
    <p>{{ profile.get_sex_display }}</p>
    <p>{{ profile.introduction }}</p>
{% endwith %}
</div>
{% if user.username == request.user.username %}
    <span><a href="{% url 'profile_edit' %}">编辑个人资料</a></span>
    {% else %}
    <span>
        <a href="#" data-id="{{ user.id }}" data-action="{% if request.user in user.followers.all %}un{% endif %}follow"
    class="followbutton">
    {% if request.user not in user.followers.all %}
        关注
        {% else %}
        取消关注
    {% endif %}
    </a>
    </span>
{% endif %}

    <div class="count">
    关注者<span class="followers-count">{{ user.followers.count }}</span>
    关注了<span class="following-count">{{ user.following.count }}</span>
    </div>

    <div class="activity-stream">动态
    {% for action in actions %}
        <div>
            {{ action.verb }}
                <span><a href="{{ action.target.get_absolute_url }}">{{ action.target }}</a> {{ action.created }}</span>
        </div>
    {% endfor %}
    </div>

{% endblock %}

{% block domready %}
    $('a.followbutton').click(function (e) {
        e.preventDefault();
        $.post('{% url 'user_follow' %}',
            {
                id: $(this).data('id'),
                action: $(this).data('action')
            },
        function (data) {
            if(data['status'] == 'ok'){
                var previous_action = $('a.followbutton').data('action');

                    // toggle data-action
                $('a.followbutton').data('action', previous_action == 'follow' ? 'unfollow' : 'follow');
                    // toggle link text
                $('a.followbutton').text(previous_action == 'follow' ? '取消关注' : '关注');

                    // update total followers
                var previous_followers = parseInt($('span.followers-count').text());
                $('span.followers-count').text(previous_action == 'follow' ? previous_followers + 1 : previous_followers - 1);
            }
        });
    });
{% endblock %}

core/templates/core/question.html
{% extends 'base.html' %}

{% block title %}{{ question.title }}{% endblock %}

{% block content %}
{% for question in questions %}
    <h2>
    <a href="{{ question.get_absolute_url }}">
        {{ question.title }}
    </a>
    </h2>
    <p>
    编辑于 {{ question.created }} by {{ question.author }}
    </p>
    <hr>
{% endfor %}
{% endblock %}

core/templates/core/question_detail.html
{% extends 'base.html' %}

{% load awesome_tags %}
{% block title %}{{ question.title }}{% endblock %}
{% block content %}
    <div class="ui segement">
        <div class="ui container grid">
            <div class="eleven wide column">
                <div class="ui very relaxed horizontal list">
                    <div class="item">
                        <a class="button primary" href="#">1</a>
                    </div>
                    <div class="item">
                        <a class="button primary" href="#">2</a>
                    </div>
                    <div class="item">
                        <a class="button primary" href="#">3</a>
                    </div>
                </div>
                <div class="content">
                    <h2 class="ui header">{{ question.title }}</h2>
                    <div class="description">
                        {{ question.body }}
                    </div>
                </div>
            </div>

            <div class=" five wide column">
                <div class="ui small statistics">
                    <div class="statistic">
                        <div class="label">
                            关注者
                        </div>
                        <div class="value">
                            5,550
                        </div>

                    </div>
                    <div class="statistic">

                        <div class="label">
                            被浏览
                        </div>
                        <div class="value">
                            5,550
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="ui segment">

        <div class="ui container grid">
            <div class="eleven wide column">
                <div class="content">
                    <div class="ui buttons right floated">
                        <a class="ui button">默认排序</a>
                        <a class="ui button">时间排序</a>
                    </div>
                    <div class="ui header">{{ question.answers_count }}个回答
                    </div>

                </div>
                <div class="ui list">
                    {% for answer in answers %}
                    <div class="item">
                    {{ answer.body|linebreaks }}
                    </div>
                        <hr class="ui divider">
                    {% endfor %}

                </div>

                    <h3 class="ui header">撰写答案</h3>

                        <form class="ui form" action="." method="post">
                            {% csrf_token %}
                            <div class="field">
                                <textarea name="body" id="answer"></textarea>
                            </div>
                            <button class="ui button" type="submit">提交回答</button>
                        </form>


            </div>
            <div class="five wide column">
                {% similar_questions question %}
            </div>
        </div>
    </div>
{% endblock %}

core/templates/core/question_rank.html
{% extends 'base.html' %}

{% block title %}
浏览最多
{% endblock %}

{% block content %}
<h1>最热问题</h1>

    <ol>
    {% for question in most_viewd %}
        <li>
            <a href="{{ question.get_absolute_url }}">{{ question.title }}</a>
        </li>
    {% endfor %}

    </ol>


{% endblock %}

core/templates/core/similar_questions.html
    <h3 class="ui header">相关问题</h3>
    {% for question in questions %}
        <div class="content">
            <div class="summary">
                <a href="{{ question.get_absolute_url }}">{{ question.title }}</a>
                {{ question.answers_count }}个回答
            </div>
        </div>
    {% endfor %}

core/templates/core/topics.html
{% extends 'base.html' %}

{% block title %}标签{% endblock %}

{% block content %}
    {% with topics.count as totoal_topics %}
        <h2>{{ totoal_topics }}个话题</h2>
    {% endwith %}
{% for topic in topics %}
<ul>
<li><a href="#">{{ topic.name }}</a></li>
</ul>
{% endfor %}

{% endblock %}