account/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    #url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'^register/$', views.register, name='register'),
]

core/urls.py
from django.conf.urls import url

from . import views
import account

urlpatterns = [
    url(r'^activity/$', views.activity, name='activity'),
    url(r'^ranking/$', views.question_ranking, name='ranking'),
    url(r'^question/$', views.question, name='question'),
    url(r'^question/(?P<id>\d+)/$', views.question_detail, name='question_detail'),
    url(r'^topic/$', views.topic, name='topic'),
    url(r'^people/edit/$', account.views.profile_edit, name='profile_edit'),
    url(r'^people/follow/$', views.user_follow, name='user_follow'),
    url(r'^people/(?P<username>[-\w]+)/$', views.people, name='people'),
    url(r'^question/ask/$', views.create_question, name='ask'),
]

fakezhihu/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from core.views import index, search
urlpatterns = [
    # Examples:
    # url(r'^$', index, name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls',
                              namespace='account')),

    url(r'^', include('core.urls')),
    # 主页
    url(r'^$', index, name='index'),
    url(r'^q/$', search, name='search'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

from taggit.managers import TaggableManager

class Question(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, related_name='questions')
    body = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    topics = TaggableManager()

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('question_detail',
                       args=[self.id])

    def answers_count(self):
        return self.answers.count()


class Answer(models.Model):
    question = models.ForeignKey(Question, related_name='answers')
    author = models.ForeignKey(User, related_name='answers')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    body = models.TextField()

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.body


class Action(models.Model):
    user = models.ForeignKey(User,
                             related_name='actions',
                             db_index=True)
    verb = models.CharField(max_length=255)
    target_ct = models.ForeignKey(ContentType,
                                  blank=True,
                                  null=True,
                                  related_name='target_obj')
    target_id = models.PositiveIntegerField(null=True,
                                            blank=True,
                                            db_index=True)
    target = GenericForeignKey('target_ct', 'target_id')
    created = models.DateTimeField(auto_now_add=True,
                                   db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{self.user} {self.verb} {self.target} at {self.created}'.format(self=self)

    def get_target_model_name(self):
        return self.target_ct.model_class().__name__

core/forms.py
from django import forms

from .models import Answer, Question

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('body',)
        labels = {
            'body': '撰写答案',
        }


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('title', 'body')
        labels = {
            'body': '问题描述(可选)',
        }

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.models import User
from django.db.models import Count
from django.views.decorators.http import require_POST
from django.contrib import messages

from taggit.models import Tag

from redis import StrictRedis, ConnectionPool

from account.models import Contact
from .models import Question, Action
from .forms import AnswerForm, QuestionForm
from .utils import create_action
from .decorators import ajax_required

pool = ConnectionPool(host=settings.REDIS_HOST,
                      port=settings.REDIS_PORT,
                      db=settings.REDIS_DB)
r = StrictRedis(connection_pool=pool)


@login_required
def activity(request):
    actions = Action.objects.exclude(user=request.user)
    following_ids = request.user.following.values_list('id', flat=True)
    if following_ids:
        actions = actions.filter(user_id__in=following_ids) \
            .select_related('user', 'user__profile') \
            .prefetch_related('target')

    return render(request,
                  'core/activity.html',
                  {'actions': actions})


@login_required
def question(request):
    questions = Question.objects.all()

    return render(request,
                  'core/question.html',
                  {'questions': questions})


@login_required
def question_ranking(request):
    question_ranking = r.zrange('question_ranking', 0, -1,
                                desc=True)[:10]
    question_ranking_ids = [int(id) for id in question_ranking]
    most_viewd = list(Question.objects.filter(id__in=question_ranking_ids))
    most_viewd.sort(key=lambda x: question_ranking_ids.index(x.id))

    return render(request,
                  'core/question_rank.html',
                  {'most_viewd': most_viewd})


# 首页视图转到这里
index = question


def question_detail(request, id):
    question = get_object_or_404(Question, pk=id)
    answers = question.answers.all()
    # total_views = r.incr('question:{}:views'.format(question.id))
    # r.zincrby('question_ranking', question.id, 1)

    if request.method == 'POST':
        answer_form = AnswerForm(request.POST)
        '''
        if question.answers.filter(author=request.user).exists():
            messages.error(request, '你已回答过此问题了！')
            return redirect(question)
        '''
        if answer_form.is_valid():
            new_answer = answer_form.save(commit=False)
            new_answer.question = question
            new_answer.author = request.user
            new_answer.save()
            create_action(request.user, '回答了问题', question)
            return redirect(question)
    else:
        answer_form = AnswerForm()
    return render(request,
                  'core/question_detail.html',
                  {'question': question,
                   'answers': answers,
                   'answer_form': answer_form})


@login_required
def topic(request):
    topics = Tag.objects.all()
    return render(request,
                  'core/topics.html',
                  {'topics': topics})


def people(request, username):
    user = get_object_or_404(User, username=username)
    actions = Action.objects.filter(user=user)
    return render(request,
                  'core/people.html',
                  {'user': user, 'actions': actions})


@login_required
def create_question(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            new_question = form.save(commit=False)
            new_question.author = request.user
            new_question.save()
            messages.success(request, '你问了一个问题')
            return redirect(reverse('question'))
    else:
        form = QuestionForm()

    return render(request, 'core/ask.html',
                  {
                      'form': form
                  })


@require_POST
@ajax_required
@login_required
def user_follow(request):
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    if user_id and action:
        try:
            user = User.objects.get(pk=user_id)
            if action == 'follow':
                Contact.objects.get_or_create(user_from=request.user,
                                              user_to=user)
                create_action(request.user, '关注了用户', user)
            else:
                Contact.objects.filter(user_from=request.user,
                                       user_to=user).delete()
            return JsonResponse({'status': 'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status': 'ko'})
    return JsonResponse({'status': 'ko'})


def search(request):
    word = request.GET.get('word')
    if not word:
        return JsonResponse({'error': 'You got nothing'})
    return JsonResponse({'success': 'Will be complete soon!'})

core/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}知乎，与世界分享你的故事{% endblock %}</title>
    <link href="{% static 'css/semantic.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/semantic.min.js' %}"></script>
    <script src="https://cdn.bootcss.com/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>

    <style type="text/css">
        body {
        }

        .ui.menu .item img.logo {
            margin-right: 1.5em;
        }

        .main.container {
            margin-top: 7em;
        }

        .ui.footer.segment {
            margin: 5em 0em 0em;
            padding: 5em 0em;
        }
    </style>
</head>
<body>
<!-- navbar begins -->
<div class="ui menu">
    <div class="ui container">
        {% url 'index' as i %}
        {% url 'question' as q %}
        {% url 'topic' as t %}
        {% url 'activity' as a %}
        <a href="{{ i }}" class="header {% if request.path == i %} active {% endif %} item">
            伪乎
        </a>
        <a href="{{ q }}" class="{% if request.path == q %} active {% endif %} item">问题</a>
        <a href="{{ t }}" class="{% if request.path == t %} active {% endif %} item">话题</a>
        <a href="{{ a }}" class="{% if request.path == a %} active {% endif %} item">动态</a>
        <div class="item">
            <form action="{% url 'search' %}" method="get">
                <div class="ui icon input">
                    <input placeholder="Search..." type="text">
                    <i class="search link icon"></i>
                </div>
            </form>
        </div>
        <div class="item">
            <a class="ui primary button" href="{% url 'ask' %}">
                提问
            </a>
        </div>

        <!-- menu right begins -->
        <div class="right menu">

            {% if request.user.is_authenticated %}
                <div class="ui simple right floated dropdown item">
                    <a href="#" class="ui primary button">{{ request.user }} <i class="dropdown icon"></i></a>
                    <div class="menu transition" tabindex="-1">
                        <a class="item" href="{{ request.user.get_absolute_url }}">主页</a>
                        <a class="item" href="{% url 'account:logout' %}">退出</a>
                    </div>
                </div>
            {% else %}

                <div class="right menu">
                    <div class="item">
                        <a class="ui button" href="{% url 'account:login' %}">登录</a>
                    </div>
                    <div class="item">
                        <a class="ui primary button" href="{% url 'account:register' %}">加入我们</a>
                    </div>
                </div>


            {% endif %}
        </div>
        <!-- menu right ends -->
    </div>

</div>
<!-- navbar ends -->


<div class="segement message is-info">
    {% if messages %}
        <div class="message-body">

            <ul class="list">
                {% for message in messages %}
                    <li class="{{ message.tags }}">
                        {{ message|safe }}
                    </li>
                {% endfor %}
            </ul>

        </div>
    {% endif %}
</div>

{% block content %}{% endblock %}


<!-- footer begins here -->
<div class="ui inverted vertical footer segment">
    <div class="ui center aligned container">
        <div class="ui stackable inverted divided grid">
            <div class="three wide column">
                <h4 class="ui inverted header">Group 1</h4>
                <div class="ui inverted link list">
                    <a href="#" class="item">Link One</a>
                    <a href="#" class="item">Link Two</a>
                    <a href="#" class="item">Link Three</a>
                    <a href="#" class="item">Link Four</a>
                </div>
            </div>
            <div class="three wide column">
                <h4 class="ui inverted header">Group 2</h4>
                <div class="ui inverted link list">
                    <a href="#" class="item">Link One</a>
                    <a href="#" class="item">Link Two</a>
                    <a href="#" class="item">Link Three</a>
                    <a href="#" class="item">Link Four</a>
                </div>
            </div>
            <div class="three wide column">
                <h4 class="ui inverted header">Group 3</h4>
                <div class="ui inverted link list">
                    <a href="#" class="item">Link One</a>
                    <a href="#" class="item">Link Two</a>
                    <a href="#" class="item">Link Three</a>
                    <a href="#" class="item">Link Four</a>
                </div>
            </div>
            <div class="seven wide column">
                <h4 class="ui inverted header">Footer Header</h4>
                <p>Extra space for a call to action inside the footer that could help re-engage users.</p>
            </div>
        </div>
        <div class="ui inverted section divider"></div>
        <img src="assets/images/logo.png" class="ui centered mini image">
        <div class="ui horizontal inverted small divided link list">
            <a class="item" href="#">Site Map</a>
            <a class="item" href="#">Contact Us</a>
            <a class="item" href="#">Terms and Conditions</a>
            <a class="item" href="#">Privacy Policy</a>
        </div>
    </div>
</div>
<!-- footer ends here>

<!-- scripts begin here -->
<script>
    var csrftoken = $.cookie('csrftoken');

    function csrfSafeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomin) {
                xhr.setRequestHeader('X-CSRFToken', csrftoken);
            }
        }
    });
    $(document).ready(function () {
        {% block domready %}
        {% endblock %}
    });

</script>
<!-- scripts end here -->
</body>
</html>